# GitHub Action for generating a contribution snake grid

name: Generate Snake Animation

# Controls when the action will run
on:
  # runs automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
    
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - main
    - master

# The sequence of runs in this workflow
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v3

      # Generates the snake
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: GodEyeTee
          # snake eating contribution graph options
          svg_out_path: dist/github-contribution-grid-snake.svg
          svg_out_path_dark: dist/github-contribution-grid-snake-dark.svg

      # Push to GitHub
      - name: Push changes
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # ถ้าใช้ Personal Access Token แทน
          # GITHUB_TOKEN: ${{ secrets.PAT }}
